### PR TITLE
Add support for uncached physical addresses and add .gitignore

### PR DESCRIPTION
**Pull request by ffainelli**

### CODE REVIEW

**Comment by ffainelli** [comment]
The first patch was also submitted to Charles Cazabon for review, he has not responded yet, so maybe it will be part of an upcoming memtester official release, maybe not. We find it useful regardless.

**Comment by ffainelli** [comment]
He is usually responsive in your experience? Would you want me to submit the second commit adding .gitignore separately?

**Comment by jnavila** [comment]
I don't remember, this was a long time ago. If there's no news from him in one week, I'll merge your PR.

**Comment by lucaceresoli** [comment]
FYI, I sent some patches last February, Charles replied a few hours later:

> At this point in memtester's history, I'm not really interested in adding new
> features unless they have been tested on all the platforms memtester supports.
> That testing was a *huge* part of the effort of the complete rewrite I did in
> v4.

So I would expect to see no further developments except maybe for small fixes.

If @jnavila is fine with accepting new features here, creating de facto a fork, then I'd be happy to send my improvement here as well.
Here it is, for the curious: [Suppress progress output if stdout is not a tty](https://github.com/lucaceresoli/memtester/commit/026768d9e5fa344cd115596d70e3b24a1b1387ae)

**Comment by jnavila** [comment]
@lucaceresoli  This is a critical point for this project. Unfortunately, I only test on my Linux embedded system, with some specific options.

BTW your patch is much better than mine. i'm eager to merge it with the additional option.

**Comment by lucaceresoli** [comment]
> BTW your patch is much better than mine. i'm eager to merge it with the additional option.

Good, I'm sending you a pull request.

**Pull request merged**
